[package]
name = "tudu"
version = "1.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "Manage your tasks with a simple but powerful system"
repository = "https://github.com/SamYouatt/tudu"
readme = "README.md"
publish = true

[dependencies]
chrono = "0.4.26"
